# Server
server:
  port: 8080

  # Context path of the application
  servlet:
    context-path: /api

    # Default HTTP session time out
    session:
      timeout: 15m

  # Which baseurl:port to show in response
  forward-headers-strategy: FRAMEWORK

# Spring
spring:
  application:
    name: RP-FIT

  # JDBC
  datasource:
    default:
      jdbc-url: jdbc:h2:mem:fitdb;DB_CLOSE_DELAY=-1;MODE=MSSQLServer
      username: sa
      driver-class-name: org.h2.Driver
      password:

    eventstore:
      jdbc-url: jdbc:h2:mem:rp-fit-eventstore;DB_CLOSE_DELAY=-1;MODE=MSSQLServer
      username: sa
      driver-class-name: org.h2.Driver
      password:

  # Liquibase
  liquibase:
    default:
      url: jdbc:h2:mem:fitdb;DB_CLOSE_DELAY=-1
      user: sa
      password:
      change-log: classpath:db/changelog/fit/db.changelog-master.xml
    event-store:
      url: jdbc:h2:mem:rp-fit-eventstore;DB_CLOSE_DELAY=-1
      user: sa
      password:
      change-log: classpath:db/changelog/eventstore/db.changelog-master.xml

  # Redis
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5000
      lettuce:
      pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
# SpringDoc
springdoc:
  swagger-ui:
    path: /api-docs.html
    oath:
      use-pkce-with-authorization-code-grant: true
      client-id: rp-fit-app

# Logging
